import env from './env';

export const API_CONFIG = {
  timeout: 10000,
  baseURL: env.api.url,
  endpoints: {
    auth: {
      login: '/auth/login',
      loginGoogle: '/auth/login/google',
      register: '/auth/register',
      verify: '/auth/verify',
      refresh: '/auth/refresh',
      logout: '/auth/logout',
      update: '/auth/update',
    },
    user: {
      find: '/users',
      findById: (id: string) => `/users/${id}`,
      create: '/users',
      update: (id: string) => `/users/${id}`,
      delete: (id: string) => `/users/${id}`,
    },
    role: {
      find: '/roles',
      findById: (id: string) => `/roles/${id}`,
      create: '/roles',
      update: (id: string) => `/roles/${id}`,
      delete: (id: string) => `/roles/${id}`,
    },
    permission: {
      find: '/permissions',
      findById: (id: string) => `/permissions/${id}`,
      create: '/permissions',
      update: (id: string) => `/permissions/${id}`,
      delete: (id: string) => `/permissions/${id}`,
    },
    profile: {
      me: '/profiles/me',
      find: '/profiles',
      findById: (id: string) => `/profiles/${id}`,
      create: '/profiles',
      update: (id: string) => `/profiles/${id}`,
      delete: (id: string) => `/profiles/${id}`
    },
    author: {
      find: '/authors',
      findById: (id: string) => `/authors/${id}`,
      create: '/authors',
      update: (id: string) => `/authors/${id}`,
      delete: (id: string) => `/authors/${id}`,
    },
    category: {
      find: '/categories',
      findById: (id: string) => `/categories/${id}`,
      create: '/categories',
      update: (id: string) => `/categories/${id}`,
      delete: (id: string) => `/categories/${id}`,
    },
    book: {
      find: '/books',
      findById: (id: string) => `/books/${id}`,
      create: '/books',
      update: (id: string) => `/books/${id}`,
      delete: (id: string) => `/books/${id}`,
    },
    file: {
      find: '/files',
      findByUser: '/files/user',
      findById: (id: string) => `/files/${id}`,
      download: (id: string) => `/files/${id}/download`,
      upload: '/files/upload',
      uploadPresigned: '/files/upload/presigned',
      completePresignedUpload: '/files/upload/complete',
      delete: (id: string) => `/files/${id}`,
      view: (id: string) => `/files/${id}/view`,
    },
    image: {
      upload: '/images/upload',
      delete: (url: string) => `/images/${url}`,
    },
    borrow: {
      find: '/borrows',
      history: '/borrows/history',
      findById: (id: string) => `/borrows/${id}`,
      create: '/borrows',
      update: (id: string) => `/borrows/${id}`,
      delete: (id: string) => `/borrows/${id}`,
      extend: (id: string) => `/borrows/${id}/extend`,
      return: (id: string) => `/borrows/${id}/return`,
      read: (id: string) => `/borrows/${id}/read`,
    },
    bookmark: {
      find: '/bookmarks',
      findById: (id: string) => `/bookmarks/${id}`,
      status: '/bookmarks/status',
      create: '/bookmarks',
      update: (id: string) => `/bookmarks/${id}`,
      delete: (id: string) => `/bookmarks/${id}`,
    },
    collection: {
      find: '/collections',
      findById: (id: string) => `/collections/${id}`,
      create: '/collections',
      update: (id: string) => `/collections/${id}`,
      delete: (id: string) => `/collections/${id}`,
    },
    review: {
      find: '/reviews',
      findById: (id: string) => `/reviews/${id}`,
      create: '/reviews',
      update: (id: string) => `/reviews/${id}`,
      delete: (id: string) => `/reviews/${id}`,
    },
  },
};

export default API_CONFIG;
