const paths = {
  home: '/',
  dashboard: '/dashboard',
  ecommerce: '/ecommerce',
  calendar: '/calendar',
  profile: '/profile',
  formElements: '/form-elements',
  basicTables: '/basic-tables',
  blank: '/blank',
  error404: '/404',
  lineChart: '/line-chart',
  barChart: '/bar-chart',
  alerts: '/alerts',
  avatars: '/avatars',
  badge: '/badge',
  buttons: '/buttons',
  images: '/images',
  videos: '/videos',
  signin: '/signin',
  signup: '/signup',
  search: '/search',
  books: '/books',
  book: (slug: string | undefined) => `/books/${slug}`,
};

export default paths;
